name: Build map

on:
  workflow_dispatch:

jobs:
  motomap-container-job:
    runs-on: ubuntu-latest
    container:
      image: tmesot/motomap:refactor
      env:
        MAP_LIST: ${{ github.event.inputs.map_list }}}}
      volumes:
        - /output_volume:/motomap/output
    steps:
      - name: Run script
        run: /motomap/motomap.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maps files
          path: /output_volume
