name: Build map

on:
  workflow_dispatch:
    inputs:
      maps_list:
        description: 'List of map to generate (semi-colon separated, geofabrik path format)'
        default: 'antarctica;europe/andorra;europe/france/guyane'
        required: true
        type: string
      maps_design:
        description: 'Design to use for generated map'
        default: 'default'
        required: true
        type: string

jobs:
  motomap-container-job:
    runs-on: ubuntu-latest
    container:
      image: tmesot/motomap:refactor
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      env:
        MAPS_LIST: ${{ github.event.inputs.maps_list }}
        MAPS_DESIGN: ${{ github.event.inputs.maps_design }}
    steps:
      - name: Run script
        run: bash /motomap/motomap/motomap.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Generate map artefact
          path: /motomap/output
